#!/bin/bash -l
#SBATCH -N 1
#SBATCH -t 00:1:00
#SBATCH -J job-benchmark
#SBATCH -o job/output

export MKL_NUM_THREADS=1

srun -N 1 -n 1 ./.build/bin/benchmark-blas
echo
srun -N 1 -n 1 ./.build/bin/benchmark-blocked
echo
srun -N 1 -n 1 ./.build/bin/benchmark-naive
